[build]
  publish = "public"
  command = """
      curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz &&
      tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz &&
      rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz &&
      export PATH=/opt/build/repo/dart-sass:$PATH &&
      hugo --gc --minify
    """

[build.environment]
  HUGO_VERSION = "0.136.4"   # Specify the Hugo version you're using
  NODE_VERSION = "18.20.4"   # Ensure Netlify uses a compatible Node.js version (or whatever is needed for Dart Sass)
  DART_SASS_VERSION = "1.79.2"  # Specify the Dart Sass version

[context.production.environment]
  HUGO_ENV = "production"

# If you need Hugo extended version (for SASS/SCSS support)
# [build.environment]
#   HUGO_EXTENDED = "true"

# Cache npm dependencies between builds for faster builds
# [[plugins]]
#   package = "@netlify/plugin-cache"
