# when using the default proxy server port
# local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "settings"
    label: "settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "General settings"
        file: "hugo.yaml"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "logo", label: "Logo", widget: "image" }


  - name: "home"
    label: "Home page"
    editor:
      preview: false
    files:
      - name: "hero"
        label: "Hero Section"
        file: "data/home/hero.yml"
        fields:
          - { name: "intro", label: "Intro", widget: "string" }
          - { name: "title", label: "Title", widget: "string" }
          - name: "image"
            label: "Image"
            widget: "object"
            fields:
              - { name: "url", label: "URL", widget: "image" }
              - { name: "alt", label: "Alt Text", widget: "string" }
          - { name: "video_id", label: "Video id", widget: "string" }


      - name: "spotify"
        label: "Spotify Section"
        file: "data/home/spotify.yml"
        fields:
          - { name: "intro", label: "Intro", widget: "string" }
          - { name: "title", label: "Title", widget: "string" }
          - name: "spotify"
            label: "Spotify"
            widget: "object"
            fields:
              - { name: "type", label: "Type", widget: "select", options: ["album", "track", "artist"] }
              - { name: "id", label: "ID", widget: "string" }


      - name: "about"
        label: "About Section"
        file: "data/home/about.yml"
        fields:
          - { name: "intro", label: "Intro", widget: "string" }
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }
          - { name: "image", label: "Image", widget: "image" }
          - name: "link"
            label: "Link"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "url", label: "Page", widget: "string" }



      - name: "gallery"
        label: "Gallery Section"
        file: "data/home/gallery.yml"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - name: "images"
            label: "Images"
            widget: "list"
            required: true
            fields:
            - { name: "name", label: "Name", widget: "sting" }
            - { name: "url", label: "Url", widget: "image" }

  - name: "about"
    label: "About page"
    file: ""
    files:
      - name: "about"
        label: "About Section"
        file: "content/about/_index.md"
        create: false
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "description", widget: "text" }
          - { name: "body", label: "Content", widget: "markdown" }
          - { name: "image", label: "Image", widget: "image" }

      - name: "gallery"
        label: "Gallery Section"
        file: "data/about/gallery.yml"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - name: "images"
            label: "Images"
            widget: "list"
            required: true
            fields:
            - { name: "name", label: "Name", widget: "sting" }
            - { name: "url", label: "Url", widget: "image" }


  - name: "gallery"
    label: "Gallery page"
    file: ""
    files:
      - name: "gallery"
        label: "Gallery Section"
        file: "content/gallery/_index.md"
        create: false
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "description", widget: "string" }


  - name: "contact"
    label: "Contact page"
    file: ""
    files:
      - name: "contact"
        label: "Contact Section"
        file: "content/contact/_index.md"
        create: false
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }



  - name: "galleries"
    label: "Galleries"
    folder: "content/gallery"
    create: true
    editor:
      preview: false
    label_singular: 'Gallery'
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    filter: { field: "visible", value: true }
    fields:
      - {label: "Visible", name: "visible", widget: hidden, default: true}
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Datum", widget: "datetime", date_format: "YYYY.MM.DD" }
      - { name: "cover_image", label: "Cover image", widget: "image",  }
      - { name: "description", label: "Beschrijving", widget: "text" }
      - {
          name: "images",
          label: "Album Images",
          widget: "image",
          required: true,
        }
